packages = ["pillow", "numpy", "coolname", "beartype"]

[files]
"./workerlib.py" = ""
"./Steganography.py" = ""
"./images/lock.png" = ""
"./images/key.png" = ""
"./gettext/en.mo" = "./gettext/en_US/LC_MESSAGES/Steganography.mo"
"./gettext/ru.mo" = "./gettext/ru_RU/LC_MESSAGES/Steganography.mo"

[adapters]
"Steganography" = ["Image", "imageToBytes", "loadImage"]
