debug = true

plugins = [
    "!codemirror",
    "!deprecations-manager",
    "!donkey",
    "!py-editor",
    "!py-game",
    "!py-terminal",
]

packages = [
    "Pillow",
    "numpy",
    "coolname",
    "beartype",
]

[files]
"./workerlib/workerlib.py" = ""
"./Steganography.py" = ""
"./gettext/en.mo" = "./gettext/en_US/LC_MESSAGES/Steganography.mo"
"./gettext/ru.mo" = "./gettext/ru_RU/LC_MESSAGES/Steganography.mo"

[adapters]
"Steganography" = [
    ["Image", "imageToJS", "imageFromJS"],
    ["Transpose", "None", "None"],
]
#"None" = ["Any", "pickle", "pickle"]
#"workerlib" = ["All", "pickle", "pickle"]
