packages = [
    "Pillow",
    "numpy",
    "beartype",
]

sync_main_only = true

[files]
"./Steganography.py" = ""

[exports]
"Steganography" = [
    "encrypt",
    "overlay",
    "prepareImage",
]

[adapters]
"Steganography" = [
    ["Image", "imageToJS", "imageFromJS"],
    ["Transpose", "None", "None"],
]
