debug = true

packages = [
    "Pillow",
    "numpy",
    "beartype",
]

sync_main_only = true

[files]
"./Steganography.py" = ""

[exports]
"Steganography" = [
    "encrypt",
    "overlay",
    "prepare",
]

[adapters]
"Steganography" = [
    ["Image", "imageToJS", "imageFromJS"],
    ["Transpose", "None", "None"],
]
#"None" = ["Any", "pickle", "pickle"]
#"workerlib" = ["All", "pickle", "pickle"]
