plugins = [
    "!codemirror",
    "!deprecations-manager",
    "!donkey",
    "!py-editor",
    "!py-game",
    "!py-terminal"
]

packages = [
    "Pillow",
    "numpy",
    "beartype"
]

sync_main_only = true

[files]
"./Steganography.py" = ""

[exports]
"Steganography" = [
    "encrypt",
    "overlay",
    "prepareImage"
]

[adapters]
"Steganography" = [
    ["Image", "imageToBytes", "loadImage"],
    ["Transpose", "None", "None"]
]
