packages = ["pillow", "numpy"] # , "beartype"]

sync_main_only = true

[files]
"./Steganography.py" = ""

[exports]
"Steganography" = ["encrypt", "overlay", "processImage"]

[adapters]
"Steganography" = ["Image", "imageToBytes", "loadImage"]
